# Generated by Django 2.2.1 on 2019-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaccountverification',
            name='type',
            field=models.IntegerField(choices=[(0, 'registration'), (1, 'password')], default=1, help_text='Decides what type of request needs to be verified.'),
        ),
    ]
