# Generated by Django 2.2.1 on 2019-05-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190510_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
