# Generated by Django 2.2.1 on 2019-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_modelaccountuser_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaccountuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
