# Generated by Django 2.2.1 on 2019-05-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190515_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaccountuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
