# Generated by Django 2.2.1 on 2019-05-20 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190515_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code of the user.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ModelAccountReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('code', models.CharField(help_text='The referrer code which are used for signup', max_length=20)),
                ('referrer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_references', to=settings.AUTH_USER_MODEL)),
                ('referrer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'account_reference',
            },
        ),
    ]
