# Generated by Django 2.2.1 on 2019-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190726_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='referral_status',
            field=models.BooleanField(default=False, help_text='check the status of referral code used or not'),
        ),
    ]
