# Generated by Django 2.2.1 on 2019-09-13 06:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_modelaccountuser_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='stripe_customer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
